services:
  create_users_db:
    image: shield_create_users_db_image
    container_name: create_users
    ports:
      - "8013:8003"
    volumes:
      - type: volume
        source: shield_volume
        target: /home/volume

  api_shield:
    depends_on:
      - create_users_db
    image: shield_api_image
    container_name: api
    ports:
      - "8000:8000" # pour ne pas avor à modifier nos commandes curl
    volumes:
      - type: volume
        source: shield_volume
        target: /home/volume

volumes:
  shield_volume:
