services:

  # dummy microservice (dev tool)
  dummy:
    pull_policy: build
    build:
      context: ../..
      dockerfile: src/docker/dummy/dummy.Dockerfile
    image: omarchoa/shield:dummy
    container_name: dummy
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models
      - type: volume
        source: users
        target: /home/shield/users

  # database microservice
  database:
    image: mariadb:10.8.2
    container_name: database
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=shield_project_db
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    volumes:
      - type: bind
        source: ~/mariadb_data
        target: /var/lib/mysql
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    ports:
        - target: 3306
          published: "3306"
    networks:
      - shield

  # api gateway
  gateway:
    depends_on:
      dummy:
        condition: service_completed_successfully
    pull_policy: build
    build:
      context: gateway
      dockerfile: gateway.Dockerfile
    image: omarchoa/shield:gateway
    container_name: gateway
    networks:
      - shield
    ports:
        - target: 8001
          published: "8001"
    volumes:
      - type: volume
        source: users
        target: /home/shield/users
        read_only: true

  # users microservice
  users:
    depends_on:
      database:
        condition: service_started
      gateway:
        condition: service_started
    pull_policy: build
    build:
      context: users
      dockerfile: Dockerfile
    image: omarchoa/shield:users
    container_name: users
    networks:
      - shield

  # data-download-prep microservice
  data-download-prep:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: build
    build:
      context: data-download-prep
      dockerfile: Dockerfile
    image: omarchoa/shield:data-download-prep
    container_name: data-download-prep
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
      - type: volume
        source: logs
        target: /home/shield/logs

  # training microservice
  training:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: build ## always build the image from a local Dockerfile
    build:
      context: ../.. ## use repo root as build context to enable Dockerfile to access files located outside of its own working directory
      dockerfile: src/docker/training/training.Dockerfile ## path to Dockerfile
    image: omarchoa/shield:training
    container_name: training
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
        read_only: true
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models

  # prediction microservice
  prediction:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: build
    build:
      context: ../..
      dockerfile: src/docker/prediction/prediction.Dockerfile
    image: omarchoa/shield:prediction
    container_name: prediction
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
        read_only: true
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models
        read_only: true

  # scoring microservice
  scoring:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: build
    build:
      context: ../..
      dockerfile: src/docker/scoring/scoring.Dockerfile
    image: omarchoa/shield:scoring
    container_name: scoring
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
        read_only: true
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models
        read_only: true


# network declarations
networks:
  shield:
    name: shield ## create network with this specific name


# volume declarations
volumes:
  data-download-prep:
    name: data-download-prep ## create volume with this specific name
  logs:
    name: logs
  models:
    name: models
  users:
    name: users
