services:

  # dummy microservice (dev tool)
  dummy:
    pull_policy: always ## always pull the image from Docker Hub
    image: ${DOCKER_HUB_REPO}:dummy
    container_name: dummy
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models

  # database microservice
  database:
    pull_policy: always
    image: ${DOCKER_HUB_REPO}:database
    container_name: database
    volumes:
      - type: bind
        source: ~/mariadb_data
        target: /var/lib/mysql
    networks:
      - shield

  # api gateway
  gateway:
    depends_on:
      dummy:
        condition: service_started
    pull_policy: always
    image: ${DOCKER_HUB_REPO}:gateway
    container_name: gateway
    networks:
      - shield
    ports:
        - target: 8001
          published: "8001"

  # users microservice
  users:
    depends_on:
      database:
        condition: service_started
      gateway:
        condition: service_started
    pull_policy: always
    image: ${DOCKER_HUB_REPO}:users
    container_name: users
    networks:
      - shield

  # data-download-prep microservice
  data-download-prep:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: always
    image: ${DOCKER_HUB_REPO}:data-download-prep
    container_name: data-download-prep
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
      - type: volume
        source: logs
        target: /home/shield/logs

  # training microservice
  training:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: always
    image: ${DOCKER_HUB_REPO}:training
    container_name: training
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
        read_only: true
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models

  # prediction microservice
  prediction:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: always
    image: ${DOCKER_HUB_REPO}:prediction
    container_name: prediction
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
        read_only: true
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models
        read_only: true

  # scoring microservice
  scoring:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: always
    image: ${DOCKER_HUB_REPO}:scoring
    container_name: scoring
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
        read_only: true
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models
        read_only: true

  # testing microservice
  testing:
    pull_policy: always
    image: ${DOCKER_HUB_REPO}:testing
    container_name: testing
    networks:
      - shield

  # frontend app
  frontend:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: always
    image: ${DOCKER_HUB_REPO}:frontend
    container_name: frontend
    networks:
      - shield
    ports:
        - target: 8501
          published: "8501"


# network declarations
networks:
  shield:
    name: shield ## create network with this specific name


# volume declarations
volumes:
  data-download-prep:
    name: data-download-prep ## create volume with this specific name
  logs:
    name: logs
  models:
    name: models
