services:

  # dummy microservice (dev tool)
  dummy:
    pull_policy: always ## always pull the image from Docker Hub
    image: omarchoa/shield:dummy
    container_name: dummy
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models

  # database microservice
  database:
    pull_policy: always
    image: mariadb:10.8.2
    container_name: database
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=shield_project_db
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    volumes:
      - type: bind
        source: ~/mariadb_data
        target: /var/lib/mysql
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d
    ports:
        - target: 3306
          published: "3306"
    networks:
      - shield

  # api gateway
  gateway:
    depends_on:
      dummy:
        condition: service_completed_successfully
    pull_policy: always
    image: omarchoa/shield:gateway
    container_name: gateway
    networks:
      - shield
    ports:
        - target: 8001
          published: "8001"

  # users microservice
  users:
    depends_on:
      database:
        condition: service_started
      gateway:
        condition: service_started
    pull_policy: always
    image: omarchoa/shield:users
    container_name: users
    networks:
      - shield

  # data-download-prep microservice
  data-download-prep:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: always
    image: omarchoa/shield:data-download-prep
    container_name: data-download-prep
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
      - type: volume
        source: logs
        target: /home/shield/logs

  # training microservice
  training:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: always
    image: omarchoa/shield:training
    container_name: training
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
        read_only: true
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models

  # prediction microservice
  prediction:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: always
    image: omarchoa/shield:prediction
    container_name: prediction
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
        read_only: true
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models
        read_only: true

  # scoring microservice
  scoring:
    depends_on:
      gateway:
        condition: service_started
    pull_policy: always
    image: omarchoa/shield:scoring
    container_name: scoring
    networks:
      - shield
    volumes:
      - type: volume
        source: data-download-prep
        target: /home/shield/data-download-prep
        read_only: true
      - type: volume
        source: logs
        target: /home/shield/logs
      - type: volume
        source: models
        target: /home/shield/models
        read_only: true


# network declarations
networks:
  shield:
    name: shield ## create network with this specific name


# volume declarations
volumes:
  data-download-prep:
    name: data-download-prep ## create volume with this specific name
  logs:
    name: logs
  models:
    name: models
