services:
  # api gateway
  gateway:
    pull_policy: always ## always pull the image from Docker Hub
    image: omarchoa/shield:gateway
    container_name: gateway
    networks:
      - shield
    ports:
      - "8001:8001"
    volumes:
      - users:/home/shield/users:ro
  # training microservice
  training:
    pull_policy: always
    image: omarchoa/shield:training
    container_name: training
    networks:
      - shield
    ports:
      - "8004:8004"
    volumes:
      - data:/home/shield/data:ro ## mount docker volume users to container path /home/shield/users with read-only permissions
      - logs:/home/shield/logs
      - models:/home/shield/models
  # prediction microservice
  prediction:
    pull_policy: always
    image: omarchoa/shield:prediction
    container_name: prediction
    networks:
      - shield
    ports:
      - "8005:8005"
    volumes:
      - data:/home/shield/data:ro
      - logs:/home/shield/logs
      - models:/home/shield/models:ro
  # scoring microservice
  scoring:
    pull_policy: always
    image: omarchoa/shield:scoring
    container_name: scoring
    networks:
      - shield
    ports:
      - "8006:8006"
    volumes:
      - data:/home/shield/data:ro
      - logs:/home/shield/logs
      - models:/home/shield/models:ro
  # dummy microservice (for debugging purposes)
  dummy:
    pull_policy: always
    image: omarchoa/shield:dummy
    container_name: dummy
    networks:
      - shield
    volumes:
      - data:/home/shield/data:ro
      - logs:/home/shield/logs:ro
      - models:/home/shield/models:ro

# network declarations
networks:
  shield:
    external: true ## look for this existing network instead of creating a new one

# volume declarations
volumes:
  data:
    external: true ## look for this existing volume instead of creating a new one
  logs:
    external: true
  models:
    external: true
  users:
    external: true
